
/**
 * Copyright (c) 2026 Fabio Orengo. All rights reserved.
 * Licensed under the MIT License.
 */

export const TOTAL_NUMBERS = 90;
export const WIN_LABELS: Record<string, string> = {
  Ambo: 'Ambo! (2)',
  Terno: 'Terno! (3)',
  Quaterna: 'Quaterna! (4)',
  Cinquina: 'Cinquina! (5)',
  Tombola: 'TOMBOLA! (15)'
};

// Full traditional Smorfia Napoletana definitions
export const SMORFIA_DEFINITIONS: Record<number, string> = {
  1: "L'Italia",
  2: "'A piccerella",
  3: "'A gatta",
  4: "'O puorco",
  5: "'A mano",
  6: "Chella che guarda 'nterra",
  7: "'O vaso",
  8: "'A Madonna",
  9: "'A figliata",
  10: "'E fasule",
  11: "'E suricille",
  12: "'E surdate",
  13: "Sant'Antonio",
  14: "'O mbriacone",
  15: "'O guaglione",
  16: "'O culo",
  17: "'A disgrazia",
  18: "'O sango",
  19: "'A resata",
  20: "'A festa",
  21: "'A femmena annura",
  22: "'O pazzo",
  23: "'O scemo",
  24: "'E guardie",
  25: "Natale",
  26: "Nanninella",
  27: "'O cantero",
  28: "'E zizze",
  29: "'O pate d'e criature",
  30: "'E palle d'o tenente",
  31: "'O padrone 'e casa",
  32: "'O capitone",
  33: "L'anni 'e Cristo",
  34: "'A capa",
  35: "L'aucielluzzo",
  36: "'E castagnelle",
  37: "'O monaco",
  38: "'E mazzate",
  39: "'A funa 'n ganna",
  40: "'A paposcia",
  41: "'O curtiello",
  42: "'O café",
  43: "'A donna onalcoppe",
  44: "'E ccancelle",
  45: "'O vino buono",
  46: "'E denare",
  47: "'O muorto",
  48: "'O muorto che parla",
  49: "'O piezzo 'e carne",
  50: "'O pane",
  51: "'O ciardino",
  52: "'A mamma",
  53: "'O viecchio",
  54: "'O cappello",
  55: "'A musica",
  56: "'A caruta",
  57: "'O scartellato",
  58: "'O paccotto",
  59: "'E pile",
  60: "Se lamenta",
  61: "'O cacciatore",
  62: "'O muorto acciso",
  63: "'A sposa",
  64: "'A sciammeria",
  65: "'O chianto",
  66: "'E ddoie zetelle",
  67: "'O totaro int'a chitarra",
  68: "'A zuppa cotta",
  69: "Sott'e 'ncoppa",
  70: "'O palazzo",
  71: "L'ommo 'e merda",
  72: "'A meraviglia",
  73: "'O spitale",
  74: "'A grotta",
  75: "Pulecenella",
  76: "'A funtana",
  77: "'E diavule",
  78: "'A bella figliola",
  79: "'O mariuolo",
  80: "'A vocca",
  81: "'E sciure",
  82: "'A tavula 'mbandita",
  83: "'O maletiempo",
  84: "'A cchiesa",
  85: "'E l'aneme d'o priatorio",
  86: "'A puteca",
  87: "'E perucchie",
  88: "'E cacecavalle",
  89: "'A vecchia",
  90: "'A paura"
};
